name: Compile Rust
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup
          run: sudo apt-get install -y libwayland-client0 libwayland-dev libasound2-dev pkg-config libusb-1.0-0-dev libftdi1-dev libudev-dev
        - name: Build
          run: cargo build --verbose