name: Compile Rust
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup
          run: sudo apt-get install libwayland-client0 libwayland-dev libasound2-dev -y
        - name: Build
          run: cargo build --verbose