name: Compile Rust
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
jobs:
    build-windows:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup
          run: sudo apt-get install -y libwayland-client0 libwayland-dev libasound2-dev pkg-config libusb-1.0-0-dev libftdi1-dev libudev-dev
        
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
          
        - name: Install MinGW
          run: sudo apt-get update && sudo apt-get install -y mingw-w64
        
        - name: Add Windows GNU Target to Rust
          run: rustup target add x86_64-pc-windows-gnu
    
        - name: Build for Windows
          run: cargo build --release --target x86_64-pc-windows-gnu

        - name: Package
          run: |
            mkdir -p package
            cp target/x86_64-pc-windows-gnu/release/flappy-bird-rust.exe package/
            cp -r assets package/
            cd package
            zip -r Flappy_Bird_Rust_windows_gnu.zip .

        - uses: actions/upload-artifact@v4
          with:
            name: flappy_bird_windows
            path: package/Flappy_Bird_Rust_windows_gnu.zip